### ISSUE TITLE
Problems with resolution and `xmonad.state`

### ISSUE THREAD

**Issue by dschrempf** [xmonad/xmonad#124]
### Problem Description

I am using two screen configurations with my laptop and whenever I boot my
laptop using its internal screen only (1366x768) after it had shut down with a
bigger screen (1920x1080), all tiling windows have size 1920x1080 and do not fit
on the space available on the internal laptop screen.

I can only get rid of this problem by setting the resolution to some value and
setting it back to the original one.

When I remove `~/.xmonad/xmonad.state`, I do not run into this problem at all.

This issue persists for months now and I believe that I read something about it
already here on Github, but I could not find the relevant issue.

$ xmonad --version
xmonad 0.13

**Comment by pjones** [comment]
This was fixed by #91.  This fix will be in the next version of xmonad.  If you would like to help us get that release out we could definitely use the help.

**Comment by dschrempf** [comment]
Hi, sorry for not coming back to you earlier. I am not yet very experienced with Haskell but willing to help. Could you please point me to some resources about how and what to contribute because the homepage is not very specific. Thanks!

**Comment by rudle** [comment]
Hi all, I'm having this same issue. At the advice of this issue, I built xmonad from source (version 0.14) and I'm sorry to say that things are not working as I'd expect. What can I do to help debug the patch made in #91?

After several attempts at starting xmonad@0.14, I still have an old state file.

```
/home/<redacted> % stat .xmonad/xmonad.state 
  File: .xmonad/xmonad.state
  Size: 1439      	Blocks: 8          IO Block: 4096   regular file
Device: 10302h/66306d	Inode: 48891575    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/    <redacted>)   Gid: ( 1000/    <redacted>)
Access: 2018-08-03 10:09:50.269365302 -0700
Modify: 2018-08-02 09:53:28.084393269 -0700
Change: 2018-08-02 09:53:28.084393269 -0700
 Birth: -
```
