### ISSUE TITLE
Optional feature to disable keeping proportion between displays for floating windows

### ISSUE THREAD

**Issue by unclechu** [xmonad/xmonad#44]
When I have displays with different resolution most of the floating windows looks broken on one of displays (usually on one with smaller resolution). See screenshots below that demonstrate the issue:

<img src="http://pix.toile-libre.org/upload/original/1472068384.png">
<img src="http://pix.toile-libre.org/upload/original/1472068426.png">

I also discussed it before on #xmonad on freenode IRC as I remember with @geekosaur , and he was approved this and said that keeping proportion for floating windows makes no sense and should be fixed.

**Comment by geekosaur** [comment]
Yes, I'm more than a bit tempted to just change the behavior. However, some people have expressed that some programs need the current behavior (notably, if it would cause something to extend past the end of the screen).

That said, I think the other behavior is still more correct most of the time. Might switch it in git and see how much trouble it causes... if I manage to get up the energy to code at some point :(

**Comment by pjones** [comment]
@geekosaur Can you describe what needs to change in xmonad for this?  Would it make a good bug for a volunteer to fix?

**Comment by liskin** [comment]
Note that https://github.com/xmonad/xmonad/pull/221 fixed some issues related to relative sizing of floats. We still store the sizing as relative to screen size, so when a workspace moves from one screen to another of a different size, floats change size even if their size should be fixed, but new floats are now always correctly sized regardless of where they appear.

I'm not sure whether it's realistic to change the floating layer to absolute sizes at this point. It's been 5 years since @geekosaur wanted to do this, and nothing really happened, and it's uncertain if such major changes make sense now that xmonad/X11 is no longer where all the exciting new development happens. :-/

**Comment by geekosaur** [comment]
Problem is, I can still crash DCSS by flipping it between different sized screens a few times (it doesn't like getting sized below 80x24). I can imagine this causing problems with other programs, as shown in the initial bug report; that's not going to be fixed by fixing xmonad sizing, it's arguably a bug in the program.
